### ISSUE TITLE
Unkown Command

### ISSUE THREAD

**Issue by redcomando1** [agnosto/fansly-scraper#1]
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$ ./fansly-scraper
-bash: ./fansly-scraper: Is a directory
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$

At one point was asking for user token however, couldn't find file where information was needed for input. 
Am on golang 1.23.1 and ubuntu on WSL for windows 10.

     Installed Via Go // 
          "go install github.com/agnosto/fansly-scraper/cmd/fansly-scraper@latest"

**Comment by redcomando1** [comment]
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$ go ./fansly-scraper
go ./fansly-scraper: unknown command
Run 'go help' for usage.

Don't know if this will help however I'll put this here anyway.

**Comment by redcomando1** [comment]
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$ go build -o fansly-scraper ./cmd/fansly-scraper
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$ go build -o fansly-scraper ./cmd/fansly-scraper
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper$ cd fansly-scraper
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$ go build -o fansly-scraper ./cmd/fansly-scraper
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$ ./fansly-scraper
2024/10/01 16:09:31 user_agent is empty in /home/bluestone/.config/fansly-scraper/config.toml

fixed however still don't know or where to add the inputs, but working on it..

**Comment by redcomando1** [comment]
To get to config
2024/10/01 16:09:31 user_agent is empty in /home/bluestone/.config/fansly-scraper/config.toml
should show $
 $      cd 
If your on windows and need to use explorer on the file location of where you are at.
$      explorer.exe .
"." is very important to open where you are at.

Testing for compatiblity on system.

**Comment by redcomando1** [comment]
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$ ./fansly-scraper
2024/10/01 16:28:23 toml: line 6 (last key "options.save_location"): invalid escape: '\ '
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$


Unknown why this is happening?

**Comment by agnosto** [comment]
if you installed via go, you shouldn't have to prefix it with `./` should just be able to run `fansly-scraper` and for windows systems when putting the path for save location you have to replace any backslashes `\` with forward slashes `/` in the path. But If you're using wsl and that's what you're going to be running it in, you should probably use that filesystem pathing so like `/mnt/i/Data/Content` for example

**Comment by redcomando1** [comment]
So I changed the save_location to /mnt/i/Data/Internet\ Archive/Fansly/Fansly\ Scraper/Fansly\ Content/
#Note that Fansly-scraper is a sub file in Fansly Scraper, Also running in wsl as linux file system so this should work as it has in the past and for other linux file options?? May need to change it or something..

Now when running command getting the following:

bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$ fansly-scraper
2024/10/02 11:14:54 toml: line 6 (last key "options.save_location"): invalid escape: '\ '
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$ fansly-scraper
2024/10/02 11:15:45 toml: line 6 (last key "options.save_location"): invalid escape: '\ '
bluestone@zserve1:/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/fansly-scraper$

Maybe because of how wsl is nested in with windows, might need to change file name.

**Comment by agnosto** [comment]
I tend to avoid spaces in directory names because it can be kind of annoying to handle, I think its just a general thing, but `\` aren't read as a normal character so you could try setting the path to `/mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/Fansly Content/` or try renaming the folders to remove the spaces in the names or use `-`  instead of a space

**Comment by redcomando1** [comment]
Alright /mnt/i/Data/Internet Archive/Fansly/Fansly Scraper/Fansly Content/ 
Works and command is working properly thank you for your help.
